### PR TITLE
Added SOAP Request in Worker

### PR DESCRIPTION
**Pull request by PedroKravetz**

### CODE REVIEW

**Comment by PedroKravetz** [comment]
I don't know what's wrong but I already signed the Contributor License Agreement, if you want me to put it here to confirm it I will

**Comment by PedroKravetz** [comment]
Captura de tela de 2022-07-18 15-26-32
Here is the photo showing that I already signed the Contributor License Agreement

**Comment by xomiamoore** [comment]
Hi @PedroKravetz, it looks like the email you used for the commit is different than the email for your GitHub account. If you add that email address to your account, it should resolve.

**Comment by PedroKravetz** [comment]
I will make another one with the correct email

**Pull request closed without merging**
