### PR TITLE
added spring-boot-starter-web

### LINKED ISSUE #308: Version 1.2.1 doesn't respond to /actuator/health
Version v1.2.1 doesn't respond to /actuator/health: connection refused.
This is because pom.xml doesn't contain dependency on spring-boot-starter-web package.

### PR DESCRIPTION
**Pull request by aanodin**
Fixes #308

### CODE REVIEW

**Comment by aanodin** [comment]
it responds on http://:8080/actuator/health with this change on java 17

**Review by saig0 — APPROVED** [review]
@aanodin LGTM. :rocket:

**Comment by saig0** [comment]
@aanodin I merged your PR. Thank you for your contribution. :tada: 

However, this community project is marked as deprecated. This means that I don't plan any further releases or contributions.

Can you use the recommended official [REST connector](https://docs.camunda.io/docs/next/components/connectors/protocol/rest/) instead?

**Comment by aanodin** [comment]
@saig0,
we plan to try the connectors instead, but for now we use this http worker. Nevermind, I already rebuilt it for us.
The new release would be useful for new users, but since nobody noticed this I think there is no any urgency here.

**Pull request merged**
